# Generated by Django 4.2.3 on 2023-07-31 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='catogry',
            new_name='category',
        ),
    ]
